language: csharp
mono: none
sudo: false
dotnet: 2.1.400
dist: trusty
script:
- bash ./travis-build.sh
env:
  global:
    secure: "RYzpD2A3pmq1lGGN/Bemrlk37jEqZSD6oWe40LQ8XHYeVUgiio/vdwhPdQNOT9y7/JK2eGzSiBfi5Z16AfKLa+/JAr2XIUKE+YhcAjlVmJrzhqRXFDLVOgtCJ1QzzV8s8f3nNgQC8Xw1y9T57wXv+u2Hrr/Xbis0cWHTDiEYyDpj2NijEdCJCyLtnR0TSoNsI4/pRp09OV5viUHgWstYiKzoHAcLTOSDtN2ARGRE51z2HWd7zCDKXi92h7t34kZ3ZTSy28wAxf/HrGX/2bLkNxERqj1KkjQ1T2K+KF4Cq8GgpTPzQpAdJCPGSSjkPHbh9HgV0QwToHfcALdHtka+o5h++OMCA91rDBP6UZgojE/9qQhZv1DEKeMLl+sRbnO+7AUsEouYFYpw0mbbI+xvtjIpRbtzRQ0WQV3k5IcBMvjB8SNSJrmSOcuPmbvJuuRlHeAUNrwELL+2kUqyQ42C+NgnpNaHUy4j/iYper/sVsg6eF7E9eBibIYMKXBtSPgkU/oV9fEDnskGeqXKSb3Vw5E9HSCEy4Hf3kgByzbVHG84OnZVq5OUQymdgvXannDRcs4aihNBSqZXM8tQQ3dxqCxQzZ9aNaBnBwddR40qJ9nflMRF6dogLqKZ23RgvWrYR2g6IYkAhPTY7XOJnKOA1xo/CmRviNSH3pKibbisjrM="
